"""contact crm fields + message scheduled_at

Revision ID: 293a529d1ba3
Revises: a611023b1e40
Create Date: 2026-06-21 12:16:50.913232

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "293a529d1ba3"
down_revision: str | None = "a611023b1e40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contact", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "contact",
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column("contact", sa.Column("company_size", sa.String(length=50), nullable=True))
    op.add_column("contact", sa.Column("industry", sa.String(length=100), nullable=True))
    op.add_column("message", sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "scheduled_at")
    op.drop_column("contact", "industry")
    op.drop_column("contact", "company_size")
    op.drop_column("contact", "tags")
    op.drop_column("contact", "notes")
    # ### end Alembic commands ###
