"""message reply-mapping fields

Revision ID: 7651e5007524
Revises: 9c532bb82702
Create Date: 2026-06-25 08:20:51.603035

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7651e5007524"
down_revision: str | None = "9c532bb82702"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("external_id", sa.String(length=128), nullable=True))
    op.add_column("message", sa.Column("account_id", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_message_external_id"), "message", ["external_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_external_id"), table_name="message")
    op.drop_column("message", "account_id")
    op.drop_column("message", "external_id")
    # ### end Alembic commands ###
