"""tenancy

Revision ID: 76b67844797b
Revises:
Create Date: 2026-06-19 20:24:19.040097

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "76b67844797b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("plan", sa.String(length=50), nullable=False),
        sa.Column("data_region", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "app_user",
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "invited", "disabled", name="userstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("sso_subject", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "email", name="uq_user_org_email"),
        sa.UniqueConstraint("sso_subject"),
    )
    op.create_index(
        op.f("ix_app_user_organization_id"), "app_user", ["organization_id"], unique=False
    )
    op.create_table(
        "workspace",
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "client", "department", "team", name="workspacekind", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "archived", name="workspacestatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("brand_voice", sa.String(), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspace_organization_id"), "workspace", ["organization_id"], unique=False
    )
    op.create_table(
        "connection",
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "gmail",
                "graph",
                "linkedin",
                name="connectionprovider",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column(
            "seat_type",
            sa.Enum(
                "email",
                "basic",
                "premium",
                "sales_nav",
                "recruiter",
                name="seattype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ok",
                "needs_reauth",
                "paused",
                name="connectionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("token_ref", sa.String(length=255), nullable=True),
        sa.Column("daily_sent", sa.Integer(), nullable=False),
        sa.Column("warmup_stage", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connection_organization_id"), "connection", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_connection_user_id"), "connection", ["user_id"], unique=False)
    op.create_table(
        "membership",
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column(
            "scope",
            sa.Enum(
                "organization", "workspace", name="membershipscope", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.String(length=26), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "org_admin",
                "workspace_admin",
                "member",
                "compliance",
                name="membershiprole",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "workspace_id", name="uq_membership_user_workspace"),
    )
    op.create_index(
        op.f("ix_membership_organization_id"), "membership", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_membership_user_id"), "membership", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_membership_workspace_id"), "membership", ["workspace_id"], unique=False
    )
    op.create_index(
        "uq_membership_user_org",
        "membership",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("scope = 'organization'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_membership_user_org",
        table_name="membership",
        postgresql_where=sa.text("scope = 'organization'"),
    )
    op.drop_index(op.f("ix_membership_workspace_id"), table_name="membership")
    op.drop_index(op.f("ix_membership_user_id"), table_name="membership")
    op.drop_index(op.f("ix_membership_organization_id"), table_name="membership")
    op.drop_table("membership")
    op.drop_index(op.f("ix_connection_user_id"), table_name="connection")
    op.drop_index(op.f("ix_connection_organization_id"), table_name="connection")
    op.drop_table("connection")
    op.drop_index(op.f("ix_workspace_organization_id"), table_name="workspace")
    op.drop_table("workspace")
    op.drop_index(op.f("ix_app_user_organization_id"), table_name="app_user")
    op.drop_table("app_user")
    op.drop_table("organization")
    # ### end Alembic commands ###
