"""agent system data model

Revision ID: 9c532bb82702
Revises: c3d4e5f6a7b8
Create Date: 2026-06-24 21:29:24.789304

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9c532bb82702'
down_revision: str | None = 'c3d4e5f6a7b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory',
    sa.Column('organization_id', sa.String(length=26), nullable=False),
    sa.Column('scope', sa.Enum('workspace', 'vertical', 'campaign', 'contact', name='memoryscope', native_enum=False, length=32), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_run', sa.String(length=26), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_organization_id'), 'memory', ['organization_id'], unique=False)
    op.create_index('ix_memory_recall', 'memory', ['organization_id', 'scope', 'scope_id'], unique=False)
    op.create_table('agent_run',
    sa.Column('workspace_id', sa.String(length=26), nullable=False),
    sa.Column('campaign_id', sa.String(length=26), nullable=True),
    sa.Column('role', sa.Enum('main', 'sourcing', 'outreach', name='agentrole', native_enum=False, length=32), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_campaign_id'), 'agent_run', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_agent_run_workspace_id'), 'agent_run', ['workspace_id'], unique=False)
    op.create_table('agent_step',
    sa.Column('run_id', sa.String(length=26), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_step_run_id'), 'agent_step', ['run_id'], unique=False)
    op.add_column('campaign', sa.Column('objective', sa.Text(), nullable=True))
    op.add_column('campaign', sa.Column('autonomy_level', sa.Enum('manual', 'assisted', 'full', name='autonomylevel', native_enum=False, length=32), server_default='assisted', nullable=False))
    op.add_column('campaign', sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('campaign', sa.Column('authored_by', sa.Enum('human', 'agent', name='authorship', native_enum=False, length=32), server_default='human', nullable=False))
    op.add_column('campaign', sa.Column('field_owners', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('campaign', sa.Column('next_source_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaign', sa.Column('brief_source', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.create_index(op.f('ix_campaign_next_source_at'), 'campaign', ['next_source_at'], unique=False)
    op.add_column('contact', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('enrollment', sa.Column('next_action', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('enrollment', sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('enrollment', sa.Column('relationship_status', sa.Enum('active', 'parked', 'nurture', 'handed_off', 'declined', name='relationshipstatus', native_enum=False, length=32), server_default='active', nullable=False))
    op.add_column('enrollment', sa.Column('park_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workspace', sa.Column('vertical', sa.String(length=50), server_default='recruiting', nullable=False))
    # Backfill existing rows, then drop the transient JSONB defaults so the DB matches the model
    # (new rows get {} from the ORM's default=dict).
    for _t, _c in (
        ("campaign", "constraints"),
        ("campaign", "field_owners"),
        ("campaign", "brief_source"),
        ("contact", "attributes"),
        ("enrollment", "next_action"),
        ("enrollment", "signals"),
    ):
        op.alter_column(_t, _c, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'vertical')
    op.drop_column('enrollment', 'park_until')
    op.drop_column('enrollment', 'relationship_status')
    op.drop_column('enrollment', 'signals')
    op.drop_column('enrollment', 'next_action')
    op.drop_column('contact', 'attributes')
    op.drop_index(op.f('ix_campaign_next_source_at'), table_name='campaign')
    op.drop_column('campaign', 'brief_source')
    op.drop_column('campaign', 'next_source_at')
    op.drop_column('campaign', 'field_owners')
    op.drop_column('campaign', 'authored_by')
    op.drop_column('campaign', 'constraints')
    op.drop_column('campaign', 'autonomy_level')
    op.drop_column('campaign', 'objective')
    op.drop_index(op.f('ix_agent_step_run_id'), table_name='agent_step')
    op.drop_table('agent_step')
    op.drop_index(op.f('ix_agent_run_workspace_id'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_campaign_id'), table_name='agent_run')
    op.drop_table('agent_run')
    op.drop_index('ix_memory_recall', table_name='memory')
    op.drop_index(op.f('ix_memory_organization_id'), table_name='memory')
    op.drop_table('memory')
    # ### end Alembic commands ###
