"""workos_org_id

Revision ID: a39ab8e4667b
Revises: c76fe691c59f
Create Date: 2026-06-20 17:31:45.661833

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a39ab8e4667b"
down_revision: str | None = "c76fe691c59f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organization", sa.Column("workos_org_id", sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, "organization", ["workos_org_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organization", type_="unique")
    op.drop_column("organization", "workos_org_id")
    # ### end Alembic commands ###
