"""audit_event + read state + notifications_seen

Revision ID: a611023b1e40
Revises: b68204428c41
Create Date: 2026-06-21 00:04:00.559550

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a611023b1e40"
down_revision: str | None = "b68204428c41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("workspace_id", sa.String(length=26), nullable=True),
        sa.Column("actor_user_id", sa.String(length=26), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=26), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_event_action"), "audit_event", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_event_organization_id"), "audit_event", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_event_workspace_id"), "audit_event", ["workspace_id"], unique=False
    )
    op.add_column(
        "app_user", sa.Column("notifications_seen_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "enrollment", sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("enrollment", "last_read_at")
    op.drop_column("app_user", "notifications_seen_at")
    op.drop_index(op.f("ix_audit_event_workspace_id"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_organization_id"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_action"), table_name="audit_event")
    op.drop_table("audit_event")
    # ### end Alembic commands ###
