"""contact_avatar_url

Revision ID: b68204428c41
Revises: a39ab8e4667b
Create Date: 2026-06-20 18:34:09.926732

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b68204428c41"
down_revision: str | None = "a39ab8e4667b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contact", sa.Column("avatar_url", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contact", "avatar_url")
    # ### end Alembic commands ###
