"""linkedin login attempts, drop workos org id

Revision ID: beb2da1b519f
Revises: 7651e5007524
Create Date: 2026-06-25 09:28:24.078615

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "beb2da1b519f"
down_revision: str | None = "7651e5007524"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempt",
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("account_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_login_attempt_state"), "login_attempt", ["state"], unique=True)
    op.drop_constraint(op.f("organization_workos_org_id_key"), "organization", type_="unique")
    op.drop_column("organization", "workos_org_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column("workos_org_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint(
        op.f("organization_workos_org_id_key"),
        "organization",
        ["workos_org_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_login_attempt_state"), table_name="login_attempt")
    op.drop_table("login_attempt")
    # ### end Alembic commands ###
