"""data_spine

Revision ID: c76fe691c59f
Revises: 76b67844797b
Create Date: 2026-06-19 22:10:45.988809

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c76fe691c59f"
down_revision: str | None = "76b67844797b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign",
        sa.Column("workspace_id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "paused",
                "done",
                name="campaignstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "autonomy_mode",
            sa.Enum("approve_each", "auto", name="autonomymode", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("from_email", sa.String(length=320), nullable=True),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sequence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campaign_workspace_id"), "campaign", ["workspace_id"], unique=False)
    op.create_table(
        "contact",
        sa.Column("workspace_id", sa.String(length=26), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("company", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("skills", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contact_workspace_id"), "contact", ["workspace_id"], unique=False)
    op.create_table(
        "enrollment",
        sa.Column("workspace_id", sa.String(length=26), nullable=False),
        sa.Column("campaign_id", sa.String(length=26), nullable=False),
        sa.Column("contact_id", sa.String(length=26), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "proposed",
                "active",
                "awaiting_approval",
                "scheduled",
                "awaiting_reply",
                "handed_off",
                "opted_out",
                "completed",
                name="enrollmentstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("score_rationale", sa.Text(), nullable=True),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reply_pending", sa.Boolean(), nullable=False),
        sa.Column("outcome", sa.String(length=50), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaign.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["contact_id"], ["contact.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "contact_id", name="uq_enrollment_campaign_contact"),
    )
    op.create_index(op.f("ix_enrollment_campaign_id"), "enrollment", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_enrollment_contact_id"), "enrollment", ["contact_id"], unique=False)
    op.create_index(op.f("ix_enrollment_next_run_at"), "enrollment", ["next_run_at"], unique=False)
    op.create_index(op.f("ix_enrollment_state"), "enrollment", ["state"], unique=False)
    op.create_index(
        op.f("ix_enrollment_workspace_id"), "enrollment", ["workspace_id"], unique=False
    )
    op.create_table(
        "message",
        sa.Column("workspace_id", sa.String(length=26), nullable=False),
        sa.Column("enrollment_id", sa.String(length=26), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("outbound", "inbound", name="messagedirection", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum("email", "linkedin", name="channel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "approved",
                "sent",
                "failed",
                "received",
                name="messagestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["enrollment_id"], ["enrollment.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_enrollment_id"), "message", ["enrollment_id"], unique=False)
    op.create_index(op.f("ix_message_status"), "message", ["status"], unique=False)
    op.create_index(op.f("ix_message_workspace_id"), "message", ["workspace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_workspace_id"), table_name="message")
    op.drop_index(op.f("ix_message_status"), table_name="message")
    op.drop_index(op.f("ix_message_enrollment_id"), table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_enrollment_workspace_id"), table_name="enrollment")
    op.drop_index(op.f("ix_enrollment_state"), table_name="enrollment")
    op.drop_index(op.f("ix_enrollment_next_run_at"), table_name="enrollment")
    op.drop_index(op.f("ix_enrollment_contact_id"), table_name="enrollment")
    op.drop_index(op.f("ix_enrollment_campaign_id"), table_name="enrollment")
    op.drop_table("enrollment")
    op.drop_index(op.f("ix_contact_workspace_id"), table_name="contact")
    op.drop_table("contact")
    op.drop_index(op.f("ix_campaign_workspace_id"), table_name="campaign")
    op.drop_table("campaign")
    # ### end Alembic commands ###
